# Generated by Django 5.2.6 on 2025-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0011_medication_google_event_ids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiry_time", models.DateTimeField()),
            ],
        ),
    ]
